name: Deploy to Azure Container Instance

on:
  push:
    branches:
      - master
    tags:
      - 'v*.*.*' # Trigger on tags like v1.0.0

env:
  REGISTRY_URL: crblazorterminaldev.azurecr.io
  CONTAINER_APP_NAME: ca-blazorterminal-dev
  RESOURCE_GROUP: rg-blazorterminal

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout to the branch
        uses: actions/checkout@v2

      - name: Get the version
        id: get_version
        run: echo "VERSION=${GITHUB_REF#refs/tags/}" >> $GITHUB_ENV

      - name: Azure Login
        uses: azure/login@v1.4.3
        with:
          creds: ${{ secrets.CABLAZORTERMINALDEV_AZURE_CREDENTIALS }}

      - name: Build and Push Docker image to ACR
        run: |
          az acr build --registry ${{ env.REGISTRY_URL }} \
                       --file src/BlazorTerminal.Api/Dockerfile \
                       --image ${{ env.CONTAINER_APP_NAME }}:${{ env.VERSION }} \
                       .

  deploy-to-container-instance:
    runs-on: ubuntu-latest
    if: startsWith(github.ref, 'refs/tags/')
    steps:
      - name: Azure Login
        uses: azure/login@v1.4.3
        with:
          creds: ${{ secrets.CABLAZORTERMINALDEV_AZURE_CREDENTIALS }}

      - name: Create or Update Container Instance
        run: |
          az containerapp create --name ${{ env.CONTAINER_APP_NAME }} \
                              --image ${{ env.REGISTRY_URL }}/${{ env.CONTAINER_APP_NAME }}:${{ env.VERSION }} \
                              --resource-group ${{ env.RESOURCE_GROUP }} \
                              --environment cae-blazorterminal-dev \
                              --registry-server crblazorterminaldev.azurecr.io \
                              --registry-username ${{ secrets.CABLAZORTERMINALDEV_REGISTRY_USERNAME }} \
                              --registry-password ${{ secrets.CABLAZORTERMINALDEV_REGISTRY_PASSWORD }} \
                              --env-vars AZURE_APPCONFIG_CONNECTIONSTRING="${{ secrets.AZURE_APPCONFIG_CONNECTIONSTRING }}"
