name: Deploy to Azure Container Instance

on:
  push:
    branches:
      - master
  release:
    types:
      - created

env:
  REGISTRY_URL: crblazorterminaldev.azurecr.io
  CONTAINER_APP_NAME: ca-blazorterminal-dev
  RESOURCE_GROUP: rg-blazorterminal
  ENVIRONMENT_NAME: cae-blazorterminal-dev
  REGISTRY_SERVER: crblazorterminaldev.azurecr.io
  REGISTRY_USERNAME: ${{ secrets.CABLAZORTERMINALDEV_REGISTRY_USERNAME }}
  REGISTRY_PASSWORD: ${{ secrets.CABLAZORTERMINALDEV_REGISTRY_PASSWORD }}
  AZURE_APPCONFIG_CONNECTIONSTRING: ${{ secrets.AZURE_APPCONFIG_CONNECTIONSTRING }}

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    if: github.event_name == 'push'
    steps:
      - name: Checkout to the branch
        uses: actions/checkout@v2

      - name: Azure Login
        uses: azure/login@v1.4.3
        with:
          creds: ${{ secrets.CABLAZORTERMINALDEV_AZURE_CREDENTIALS }}

      - name: Build and Push Docker image to ACR
        run: |
          az acr build --registry ${{ env.REGISTRY_URL }} \
                       --file src/BlazorTerminal.Api/Dockerfile \
                       --image ${{ env.CONTAINER_APP_NAME }}:${{ github.sha }} \
                       .

  deploy-to-container-instance:
    runs-on: ubuntu-latest
    if: github.event_name == 'release'
    steps:
      - name: Azure Login
        uses: azure/login@v1.4.3
        with:
          creds: ${{ secrets.CABLAZORTERMINALDEV_AZURE_CREDENTIALS }}

      - name: Create or Update Container Instance
        run: |
          az containerapp create --name ${{ env.CONTAINER_APP_NAME }} \
                              --image ${{ env.REGISTRY_URL }}/${{ env.CONTAINER_APP_NAME }}:${{ github.sha }} \
                              --resource-group ${{ env.RESOURCE_GROUP }} \
                              --environment ${{ env.ENVIRONMENT_NAME }} \
                              --registry-server ${{ env.REGISTRY_SERVER }} \
                              --registry-username ${{ env.REGISTRY_USERNAME }} \
                              --registry-password ${{ env.REGISTRY_PASSWORD }} \ 
                              --ingress external --target-port 80 \
                              --allow-insecure \
                              --env-vars AZURE_APPCONFIG_CONNECTIONSTRING="${{ env.AZURE_APPCONFIG_CONNECTIONSTRING }}"
