name: Trigger auto deployment for ca-blazorterminal-dev

on:
  push:
    branches:
      - master
  release:
    types:
      - created

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    if: github.event_name == 'push'
    steps:
      - name: Checkout to the branch
        uses: actions/checkout@v2

      - name: Azure Login
        uses: azure/login@v1.4.3
        with:
          creds: ${{ secrets.CABLAZORTERMINALDEV_AZURE_CREDENTIALS }}

      - name: Build and Push Docker image to ACR
        run: |
          az acr build --registry crblazorterminaldev.azurecr.io \
                       --file src/BlazorTerminal.Api/Dockerfile \
                       --image ca-blazorterminal-dev:${{ github.sha }} \
                       .
                       
  deploy-to-container-app:
    runs-on: ubuntu-latest
    if: github.event_name == 'release'
    steps:
      - name: Azure Login
        uses: azure/login@v1.4.3
        with:
          creds: ${{ secrets.CABLAZORTERMINALDEV_AZURE_CREDENTIALS }}

      - name: Deploy Docker image to Container App
        run: |
          az container-app create --name ca-blazorterminal-dev \
                                  --image crblazorterminaldev.azurecr.io/ca-blazorterminal-dev:${{ github.sha }} \
                                  --resource-group rg-blazorterminal
