name: Trigger auto deployment for ca-blazorterminal-dev

on:
  push:
    branches: 
      [ feature/ci-cd ]
    paths:
    - ".github/workflows/ca-blazorterminal-dev-AutoDeployTrigger-886d603a-159b-4f77-851e-bf7a243cf3d2.yml"
    - "src/BlazorTerminal.Api/**"
    - "src/Broker.Abstractions/**"
    - "src/Broker.SourceGenerator/**"

  workflow_dispatch:
      
jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout to the branch
        uses: actions/checkout@v2

      - name: Azure Login
        uses: azure/login@v1.4.3
        with:
          creds: ${{ secrets.CABLAZORTERMINALDEV_AZURE_CREDENTIALS }}

      - name: Build and push container image to registry
        uses: azure/container-apps-deploy-action@v1
        with:
          dockerfilePath: src/BlazorTerminal.Api/Dockerfile
          appSourcePath: ${{ github.workspace }} 
          registryUrl: crblazorterminaldev.azurecr.io
          registryUsername: ${{ secrets.CABLAZORTERMINALDEV_REGISTRY_USERNAME }}
          registryPassword: ${{ secrets.CABLAZORTERMINALDEV_REGISTRY_PASSWORD }}
          containerAppName: ca-blazorterminal-dev
          resourceGroup: rg-blazorterminal
          imageToBuild: crblazorterminaldev.azurecr.io/ca-blazorterminal-dev:${{ github.sha }}